name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install project dependencies
        run: npm ci --force
      - name: Install Angular CLI
        run: npm i --global @angular/cli
      - name: Lint code
        run: ng lint
      - name: Run unit tests
        uses: ianwalter/playwright-container@v3.0.0
        with:
          args: npm run test-headless
      - name: Build the webapp
        run: ng build
